export const REGION_DATA = [
  { city: "서울특별시", district: "송파구", regionCode: "11710" },
  { city: "서울특별시", district: "강동구", regionCode: "11740" },
  { city: "서울특별시", district: "관악구", regionCode: "11620" },
  { city: "서울특별시", district: "서초구", regionCode: "11650" },
  { city: "서울특별시", district: "동작구", regionCode: "11590" },
  { city: "서울특별시", district: "금천구", regionCode: "11545" },
  { city: "서울특별시", district: "영등포구", regionCode: "11560" },
  { city: "서울특별시", district: "강서구", regionCode: "11500" },
  { city: "서울특별시", district: "구로구", regionCode: "11530" },
  { city: "서울특별시", district: "마포구", regionCode: "11440" },
  { city: "서울특별시", district: "양천구", regionCode: "11470" },
  { city: "서울특별시", district: "서대문구", regionCode: "11410" },
  { city: "서울특별시", district: "노원구", regionCode: "11350" },
  { city: "서울특별시", district: "은평구", regionCode: "11380" },
  { city: "서울특별시", district: "강북구", regionCode: "11305" },
  { city: "서울특별시", district: "도봉구", regionCode: "11320" },
  { city: "서울특별시", district: "중랑구", regionCode: "11260" },
  { city: "서울특별시", district: "성북구", regionCode: "11290" },
  { city: "서울특별시", district: "동대문구", regionCode: "11230" },
  { city: "서울특별시", district: "광진구", regionCode: "11215" },
  { city: "서울특별시", district: "성동구", regionCode: "11200" },
  { city: "서울특별시", district: "용산구", regionCode: "11170" },
  { city: "서울특별시", district: "중구", regionCode: "11140" },
  { city: "서울특별시", district: "강남구", regionCode: "11680" },
  { city: "서울특별시", district: "종로구", regionCode: "11110" },
  // { city: "경기도", district: "수원시", regionCode: "41110" },
  { city: "경기도", district: "수원시 영통구", regionCode: "41117" },
  { city: "경기도", district: "수원시 장안구", regionCode: "41111" },
  { city: "경기도", district: "수원시 권선구", regionCode: "41113" },
  { city: "경기도", district: "수원시 팔달구", regionCode: "41115" },
  // { city: "경기도", district: "성남시", regionCode: "41130" },
  { city: "경기도", district: "성남시 수정구", regionCode: "41131" },
  { city: "경기도", district: "성남시 중원구", regionCode: "41133" },
  { city: "경기도", district: "성남시 분당구", regionCode: "41135" },
  { city: "경기도", district: "의정부시", regionCode: "41150" },
  // { city: "경기도", district: "안양시", regionCode: "41170" },
  { city: "경기도", district: "안양시 만안구", regionCode: "41171" },
  { city: "경기도", district: "안양시 동안구", regionCode: "41173" },
  { city: "경기도", district: "광명시", regionCode: "41210" },
  { city: "경기도", district: "평택시", regionCode: "41220" },
  { city: "경기도", district: "하남시", regionCode: "41450" },
  { city: "경기도", district: "동두천시", regionCode: "41250" },
  // { city: "경기도", district: "안산시", regionCode: "41270" },
  { city: "경기도", district: "안산시 상록구", regionCode: "41271" },
  { city: "경기도", district: "안산시 단원구", regionCode: "41273" },
  // { city: "경기도", district: "고양시", regionCode: "41280" },
  { city: "경기도", district: "고양시 덕양구", regionCode: "41281" },
  { city: "경기도", district: "고양시 일산동구", regionCode: "41285" },
  { city: "경기도", district: "고양시 일산서구", regionCode: "41287" },
  { city: "경기도", district: "과천시", regionCode: "41290" },
  { city: "경기도", district: "구리시", regionCode: "41310" },
  { city: "경기도", district: "남양주시", regionCode: "41360" },
  { city: "경기도", district: "오산시", regionCode: "41370" },
  { city: "경기도", district: "시흥시", regionCode: "41390" },
  { city: "경기도", district: "군포시", regionCode: "41410" },
  { city: "경기도", district: "의왕시", regionCode: "41430" },
  // { city: "경기도", district: "용인시", regionCode: "41460" },
  { city: "경기도", district: "용인시 처인구", regionCode: "41461" },
  { city: "경기도", district: "용인시 기흥구", regionCode: "41463" },
  { city: "경기도", district: "용인시 수지구", regionCode: "41465" },
  { city: "경기도", district: "파주시", regionCode: "41480" },
  { city: "경기도", district: "이천시", regionCode: "41500" },
  { city: "경기도", district: "안성시", regionCode: "41550" },
  { city: "경기도", district: "김포시", regionCode: "41570" },
  { city: "경기도", district: "화성시", regionCode: "41590" },
  { city: "경기도", district: "광주시", regionCode: "41610" },
  { city: "경기도", district: "양주시", regionCode: "41630" },
  { city: "경기도", district: "포천시", regionCode: "41650" },
  { city: "경기도", district: "여주시", regionCode: "41670" },
  { city: "경기도", district: "연천군", regionCode: "41800" },
  { city: "경기도", district: "가평군", regionCode: "41820" },
  { city: "경기도", district: "양평군", regionCode: "41830" },
  // { city: "경기도", district: "부천시", regionCode: "41190" },
  { city: "경기도", district: "부천시 오정구", regionCode: "41196" },
  { city: "경기도", district: "부천시 소사구", regionCode: "41194" },
  { city: "경기도", district: "부천시 원미구", regionCode: "41192" },
  { city: "부산광역시", district: "중구", regionCode: "26110" },
  { city: "부산광역시", district: "서구", regionCode: "26140" },
  { city: "부산광역시", district: "동구", regionCode: "26170" },
  { city: "부산광역시", district: "영도구", regionCode: "26200" },
  { city: "부산광역시", district: "부산진구", regionCode: "26230" },
  { city: "부산광역시", district: "동래구", regionCode: "26260" },
  { city: "부산광역시", district: "남구", regionCode: "26290" },
  { city: "부산광역시", district: "북구", regionCode: "26320" },
  { city: "부산광역시", district: "해운대구", regionCode: "26350" },
  { city: "부산광역시", district: "사하구", regionCode: "26380" },
  { city: "부산광역시", district: "금정구", regionCode: "26410" },
  { city: "부산광역시", district: "강서구", regionCode: "26440" },
  { city: "부산광역시", district: "연제구", regionCode: "26470" },
  { city: "부산광역시", district: "수영구", regionCode: "26500" },
  { city: "부산광역시", district: "사상구", regionCode: "26530" },
  { city: "부산광역시", district: "기장군", regionCode: "26710" },
  { city: "대구광역시", district: "남구", regionCode: "27200" },
  { city: "대구광역시", district: "서구", regionCode: "27170" },
  { city: "대구광역시", district: "중구", regionCode: "27110" },
  { city: "대구광역시", district: "동구", regionCode: "27140" },
  { city: "대구광역시", district: "북구", regionCode: "27230" },
  { city: "대구광역시", district: "수성구", regionCode: "27260" },
  { city: "대구광역시", district: "달서구", regionCode: "27290" },
  { city: "대구광역시", district: "달성군", regionCode: "27710" },
  { city: "대구광역시", district: "군위군", regionCode: "27720" },
  { city: "인천광역시", district: "중구", regionCode: "28110" },
  { city: "인천광역시", district: "동구", regionCode: "28140" },
  { city: "인천광역시", district: "미추홀구", regionCode: "28177" },
  { city: "인천광역시", district: "연수구", regionCode: "28185" },
  { city: "인천광역시", district: "남동구", regionCode: "28200" },
  { city: "인천광역시", district: "부평구", regionCode: "28237" },
  { city: "인천광역시", district: "계양구", regionCode: "28245" },
  { city: "인천광역시", district: "서구", regionCode: "28260" },
  { city: "인천광역시", district: "강화군", regionCode: "28710" },
  { city: "인천광역시", district: "옹진군", regionCode: "28720" },
  { city: "광주광역시", district: "동구", regionCode: "29110" },
  { city: "광주광역시", district: "서구", regionCode: "29140" },
  { city: "광주광역시", district: "남구", regionCode: "29155" },
  { city: "광주광역시", district: "북구", regionCode: "29170" },
  { city: "광주광역시", district: "광산구", regionCode: "29200" },
  { city: "대전광역시", district: "동구", regionCode: "30110" },
  { city: "대전광역시", district: "중구", regionCode: "30140" },
  { city: "대전광역시", district: "서구", regionCode: "30170" },
  { city: "대전광역시", district: "유성구", regionCode: "30200" },
  { city: "대전광역시", district: "대덕구", regionCode: "30230" },
  { city: "울산광역시", district: "중구", regionCode: "31110" },
  { city: "울산광역시", district: "남구", regionCode: "31140" },
  { city: "울산광역시", district: "동구", regionCode: "31170" },
  { city: "울산광역시", district: "북구", regionCode: "31200" },
  { city: "울산광역시", district: "울주군", regionCode: "31710" },
  // { city: "경상북도", district: "포항시", regionCode: "47110" },
  { city: "경상북도", district: "포항시 남구", regionCode: "47111" },
  { city: "경상북도", district: "포항시 북구", regionCode: "47113" },
  { city: "경상북도", district: "경주시", regionCode: "47130" },
  { city: "경상북도", district: "김천시", regionCode: "47150" },
  { city: "경상북도", district: "안동시", regionCode: "47170" },
  { city: "경상북도", district: "구미시", regionCode: "47190" },
  { city: "경상북도", district: "영주시", regionCode: "47210" },
  { city: "경상북도", district: "영천시", regionCode: "47230" },
  { city: "경상북도", district: "상주시", regionCode: "47250" },
  { city: "경상북도", district: "문경시", regionCode: "47280" },
  { city: "경상북도", district: "경산시", regionCode: "47290" },
  { city: "경상북도", district: "의성군", regionCode: "47730" },
  { city: "경상북도", district: "청송군", regionCode: "47750" },
  { city: "경상북도", district: "영양군", regionCode: "47760" },
  { city: "경상북도", district: "영덕군", regionCode: "47770" },
  { city: "경상북도", district: "청도군", regionCode: "47820" },
  { city: "경상북도", district: "고령군", regionCode: "47830" },
  { city: "경상북도", district: "성주군", regionCode: "47840" },
  { city: "경상북도", district: "칠곡군", regionCode: "47850" },
  { city: "경상북도", district: "예천군", regionCode: "47900" },
  { city: "경상북도", district: "봉화군", regionCode: "47920" },
  { city: "경상북도", district: "울진군", regionCode: "47930" },
  { city: "경상북도", district: "울릉군", regionCode: "47940" },
  // { city: "경상남도", district: "창원시", regionCode: "48120" },
  { city: "경상남도", district: "창원시 의창구", regionCode: "48121" },
  { city: "경상남도", district: "창원시 성산구", regionCode: "48123" },
  { city: "경상남도", district: "창원시 마산합포구", regionCode: "48125" },
  { city: "경상남도", district: "창원시 마산회원구", regionCode: "48127" },
  { city: "경상남도", district: "창원시 진해구", regionCode: "48129" },
  { city: "경상남도", district: "사천시", regionCode: "48240" },
  { city: "경상남도", district: "진주시", regionCode: "48170" },
  { city: "경상남도", district: "통영시", regionCode: "48220" },
  { city: "경상남도", district: "창녕군", regionCode: "48740" },
  { city: "경상남도", district: "김해시", regionCode: "48250" },
  { city: "경상남도", district: "밀양시", regionCode: "48270" },
  { city: "경상남도", district: "거제시", regionCode: "48310" },
  { city: "경상남도", district: "양산시", regionCode: "48330" },
  { city: "경상남도", district: "의령군", regionCode: "48720" },
  { city: "경상남도", district: "함안군", regionCode: "48730" },
  { city: "경상남도", district: "고성군", regionCode: "48820" },
  { city: "경상남도", district: "남해군", regionCode: "48840" },
  { city: "경상남도", district: "하동군", regionCode: "48850" },
  { city: "경상남도", district: "산청군", regionCode: "48860" },
  { city: "경상남도", district: "함양군", regionCode: "48870" },
  { city: "경상남도", district: "거창군", regionCode: "48880" },
  { city: "경상남도", district: "합천군", regionCode: "48890" },
  { city: "전라남도", district: "목포시", regionCode: "46110" },
  { city: "전라남도", district: "여수시", regionCode: "46130" },
  { city: "전라남도", district: "순천시", regionCode: "46150" },
  { city: "전라남도", district: "나주시", regionCode: "46170" },
  { city: "전라남도", district: "광양시", regionCode: "46230" },
  { city: "전라남도", district: "담양군", regionCode: "46710" },
  { city: "전라남도", district: "곡성군", regionCode: "46720" },
  { city: "전라남도", district: "구례군", regionCode: "46730" },
  { city: "전라남도", district: "고흥군", regionCode: "46770" },
  { city: "전라남도", district: "보성군", regionCode: "46780" },
  { city: "전라남도", district: "화순군", regionCode: "46790" },
  { city: "전라남도", district: "장흥군", regionCode: "46800" },
  { city: "전라남도", district: "강진군", regionCode: "46810" },
  { city: "전라남도", district: "해남군", regionCode: "46820" },
  { city: "전라남도", district: "영암군", regionCode: "46830" },
  { city: "전라남도", district: "무안군", regionCode: "46840" },
  { city: "전라남도", district: "함평군", regionCode: "46860" },
  { city: "전라남도", district: "영광군", regionCode: "46870" },
  { city: "전라남도", district: "장성군", regionCode: "46880" },
  { city: "전라남도", district: "완도군", regionCode: "46890" },
  { city: "전라남도", district: "진도군", regionCode: "46900" },
  { city: "전라남도", district: "신안군", regionCode: "46910" },
  // { city: "충청북도", district: "청주시", regionCode: "43110" },
  { city: "충청북도", district: "청주시 상당구", regionCode: "43111" },
  { city: "충청북도", district: "청주시 서원구", regionCode: "43112" },
  { city: "충청북도", district: "청주시 흥덕구", regionCode: "43113" },
  { city: "충청북도", district: "청주시 청원구", regionCode: "43114" },
  { city: "충청북도", district: "충주시", regionCode: "43130" },
  { city: "충청북도", district: "제천시", regionCode: "43150" },
  { city: "충청북도", district: "보은군", regionCode: "43720" },
  { city: "충청북도", district: "옥천군", regionCode: "43730" },
  { city: "충청북도", district: "영동군", regionCode: "43740" },
  { city: "충청북도", district: "증평군", regionCode: "43745" },
  { city: "충청북도", district: "진천군", regionCode: "43750" },
  { city: "충청북도", district: "괴산군", regionCode: "43760" },
  { city: "충청북도", district: "음성군", regionCode: "43770" },
  { city: "충청북도", district: "단양군", regionCode: "43800" },
  // { city: "충청남도", district: "천안시", regionCode: "44130" },
  { city: "충청남도", district: "천안시 동남구", regionCode: "44131" },
  { city: "충청남도", district: "천안시 서북구", regionCode: "44133" },
  { city: "충청남도", district: "공주시", regionCode: "44150" },
  { city: "충청남도", district: "보령시", regionCode: "44180" },
  { city: "충청남도", district: "아산시", regionCode: "44200" },
  { city: "충청남도", district: "서산시", regionCode: "44210" },
  { city: "충청남도", district: "논산시", regionCode: "44230" },
  { city: "충청남도", district: "계룡시", regionCode: "44250" },
  { city: "충청남도", district: "당진시", regionCode: "44270" },
  { city: "충청남도", district: "금산군", regionCode: "44710" },
  { city: "충청남도", district: "부여군", regionCode: "44760" },
  { city: "충청남도", district: "서천군", regionCode: "44770" },
  { city: "충청남도", district: "청양군", regionCode: "44790" },
  { city: "충청남도", district: "홍성군", regionCode: "44800" },
  { city: "충청남도", district: "예산군", regionCode: "44810" },
  { city: "충청남도", district: "태안군", regionCode: "44825" },
  { city: "세종특별자치시", district: "세종특별자치시", regionCode: "36110" },
  { city: "전북특별자치도", district: "부안군", regionCode: "52800" },
  { city: "전북특별자치도", district: "고창군", regionCode: "52790" },
  { city: "전북특별자치도", district: "순창군", regionCode: "52770" },
  { city: "전북특별자치도", district: "임실군", regionCode: "52750" },
  { city: "전북특별자치도", district: "장수군", regionCode: "52740" },
  { city: "전북특별자치도", district: "무주군", regionCode: "52730" },
  { city: "전북특별자치도", district: "진안군", regionCode: "52720" },
  { city: "전북특별자치도", district: "완주군", regionCode: "52710" },
  { city: "전북특별자치도", district: "김제시", regionCode: "52210" },
  { city: "전북특별자치도", district: "남원시", regionCode: "52190" },
  { city: "전북특별자치도", district: "정읍시", regionCode: "52180" },
  { city: "전북특별자치도", district: "익산시", regionCode: "52140" },
  { city: "전북특별자치도", district: "군산시", regionCode: "52130" },
  // { city: "전북특별자치도", district: "전주시", regionCode: "52110" },
  { city: "전북특별자치도", district: "전주시 덕진구", regionCode: "52113" },
  { city: "전북특별자치도", district: "전주시 완산구", regionCode: "52111" },
  { city: "제주특별자치도", district: "제주시", regionCode: "50110" },
  { city: "제주특별자치도", district: "서귀포시", regionCode: "50130" },
  { city: "강원특별자치도", district: "양양군", regionCode: "51830" },
  { city: "강원특별자치도", district: "고성군", regionCode: "51820" },
  { city: "강원특별자치도", district: "인제군", regionCode: "51810" },
  { city: "강원특별자치도", district: "화천군", regionCode: "51790" },
  { city: "강원특별자치도", district: "양구군", regionCode: "51800" },
  { city: "강원특별자치도", district: "철원군", regionCode: "51780" },
  { city: "강원특별자치도", district: "정선군", regionCode: "51770" },
  { city: "강원특별자치도", district: "평창군", regionCode: "51760" },
  { city: "강원특별자치도", district: "영월군", regionCode: "51750" },
  { city: "강원특별자치도", district: "횡성군", regionCode: "51730" },
  { city: "강원특별자치도", district: "홍천군", regionCode: "51720" },
  { city: "강원특별자치도", district: "속초시", regionCode: "51210" },
  { city: "강원특별자치도", district: "삼척시", regionCode: "51230" },
  { city: "강원특별자치도", district: "태백시", regionCode: "51190" },
  { city: "강원특별자치도", district: "동해시", regionCode: "51170" },
  { city: "강원특별자치도", district: "강릉시", regionCode: "51150" },
  { city: "강원특별자치도", district: "원주시", regionCode: "51130" },
  { city: "강원특별자치도", district: "춘천시", regionCode: "51110" },
];

export const CITIES = [
  "서울특별시",
  "경기도",
  "부산광역시",
  "대구광역시",
  "인천광역시",
  "광주광역시",
  "대전광역시",
  "울산광역시",
  "경상북도",
  "경상남도",
  "전라남도",
  "충청북도",
  "충청남도",
  "세종특별자치시",
  "전북특별자치도",
  "제주특별자치도",
  "강원특별자치도",
];
