export const REGION_DATA = [
  { locationName: "서울특별시 송파구", regionCode: "11710" },
  { locationName: "서울특별시 강동구", regionCode: "11740" },
  { locationName: "서울특별시 관악구", regionCode: "11620" },
  { locationName: "서울특별시 서초구", regionCode: "11650" },
  { locationName: "서울특별시 동작구", regionCode: "11590" },
  { locationName: "서울특별시 금천구", regionCode: "11545" },
  { locationName: "서울특별시 영등포구", regionCode: "11560" },
  { locationName: "서울특별시 강서구", regionCode: "11500" },
  { locationName: "서울특별시 구로구", regionCode: "11530" },
  { locationName: "서울특별시 마포구", regionCode: "11440" },
  { locationName: "서울특별시 양천구", regionCode: "11470" },
  { locationName: "서울특별시 서대문구", regionCode: "11410" },
  { locationName: "서울특별시 노원구", regionCode: "11350" },
  { locationName: "서울특별시 은평구", regionCode: "11380" },
  { locationName: "서울특별시 강북구", regionCode: "11305" },
  { locationName: "서울특별시 도봉구", regionCode: "11320" },
  { locationName: "서울특별시 중랑구", regionCode: "11260" },
  { locationName: "서울특별시 성북구", regionCode: "11290" },
  { locationName: "서울특별시 동대문구", regionCode: "11230" },
  { locationName: "서울특별시 광진구", regionCode: "11215" },
  { locationName: "서울특별시 성동구", regionCode: "11200" },
  { locationName: "서울특별시 용산구", regionCode: "11170" },
  { locationName: "서울특별시 중구", regionCode: "11140" },
  { locationName: "서울특별시 강남구", regionCode: "11680" },
  { locationName: "서울특별시 종로구", regionCode: "11110" },
  { locationName: "경기도 성남시", regionCode: "41130" },
  { locationName: "경기도 수원시 영통구", regionCode: "41117" },
  { locationName: "경기도 수원시", regionCode: "41110" },
  { locationName: "경기도 수원시 장안구", regionCode: "41111" },
  { locationName: "경기도 수원시 권선구", regionCode: "41113" },
  { locationName: "경기도 수원시 팔달구", regionCode: "41115" },
  { locationName: "경기도 성남시 수정구", regionCode: "41131" },
  { locationName: "경기도 성남시 중원구", regionCode: "41133" },
  { locationName: "경기도 성남시 분당구", regionCode: "41135" },
  { locationName: "경기도 의정부시", regionCode: "41150" },
  { locationName: "경기도 안양시", regionCode: "41170" },
  { locationName: "경기도 안양시 만안구", regionCode: "41171" },
  { locationName: "경기도 안양시 동안구", regionCode: "41173" },
  { locationName: "경기도 부천시", regionCode: "41190" },
  { locationName: "경기도 광명시", regionCode: "41210" },
  { locationName: "경기도 평택시", regionCode: "41220" },
  { locationName: "경기도 하남시", regionCode: "41450" },
  { locationName: "경기도 동두천시", regionCode: "41250" },
  { locationName: "경기도 안산시", regionCode: "41270" },
  { locationName: "경기도 안산시 상록구", regionCode: "41271" },
  { locationName: "경기도 안산시 단원구", regionCode: "41273" },
  { locationName: "경기도 고양시", regionCode: "41280" },
  { locationName: "경기도 고양시 덕양구", regionCode: "41281" },
  { locationName: "경기도 고양시 일산동구", regionCode: "41285" },
  { locationName: "경기도 고양시 일산서구", regionCode: "41287" },
  { locationName: "경기도 과천시", regionCode: "41290" },
  { locationName: "경기도 구리시", regionCode: "41310" },
  { locationName: "경기도 남양주시", regionCode: "41360" },
  { locationName: "경기도 오산시", regionCode: "41370" },
  { locationName: "경기도 시흥시", regionCode: "41390" },
  { locationName: "경기도 군포시", regionCode: "41410" },
  { locationName: "경기도 의왕시", regionCode: "41430" },
  { locationName: "경기도 용인시", regionCode: "41460" },
  { locationName: "경기도 용인시 처인구", regionCode: "41461" },
  { locationName: "경기도 용인시 기흥구", regionCode: "41463" },
  { locationName: "경기도 용인시 수지구", regionCode: "41465" },
  { locationName: "경기도 파주시", regionCode: "41480" },
  { locationName: "경기도 이천시", regionCode: "41500" },
  { locationName: "경기도 안성시", regionCode: "41550" },
  { locationName: "경기도 김포시", regionCode: "41570" },
  { locationName: "경기도 화성시", regionCode: "41590" },
  { locationName: "경기도 광주시", regionCode: "41610" },
  { locationName: "경기도 양주시", regionCode: "41630" },
  { locationName: "경기도 포천시", regionCode: "41650" },
  { locationName: "경기도 여주시", regionCode: "41670" },
  { locationName: "경기도 연천군", regionCode: "41800" },
  { locationName: "경기도 가평군", regionCode: "41820" },
  { locationName: "경기도 양평군", regionCode: "41830" },
  { locationName: "경기도 부천시 오정구", regionCode: "41196" },
  { locationName: "경기도 부천시 소사구", regionCode: "41194" },
  { locationName: "경기도 부천시 원미구", regionCode: "41192" },
  { locationName: "부산광역시 중구", regionCode: "26110" },
  { locationName: "부산광역시 서구", regionCode: "26140" },
  { locationName: "부산광역시 동구", regionCode: "26170" },
  { locationName: "부산광역시 영도구", regionCode: "26200" },
  { locationName: "부산광역시 부산진구", regionCode: "26230" },
  { locationName: "부산광역시 동래구", regionCode: "26260" },
  { locationName: "부산광역시 남구", regionCode: "26290" },
  { locationName: "부산광역시 북구", regionCode: "26320" },
  { locationName: "부산광역시 해운대구", regionCode: "26350" },
  { locationName: "부산광역시 사하구", regionCode: "26380" },
  { locationName: "부산광역시 금정구", regionCode: "26410" },
  { locationName: "부산광역시 강서구", regionCode: "26440" },
  { locationName: "부산광역시 연제구", regionCode: "26470" },
  { locationName: "부산광역시 수영구", regionCode: "26500" },
  { locationName: "부산광역시 사상구", regionCode: "26530" },
  { locationName: "부산광역시 기장군", regionCode: "26710" },
  { locationName: "대구광역시 남구", regionCode: "27200" },
  { locationName: "대구광역시 서구", regionCode: "27170" },
  { locationName: "대구광역시 중구", regionCode: "27110" },
  { locationName: "대구광역시 동구", regionCode: "27140" },
  { locationName: "대구광역시 북구", regionCode: "27230" },
  { locationName: "대구광역시 수성구", regionCode: "27260" },
  { locationName: "대구광역시 달서구", regionCode: "27290" },
  { locationName: "대구광역시 달성군", regionCode: "27710" },
  { locationName: "대구광역시 군위군", regionCode: "27720" },
  { locationName: "인천광역시 중구", regionCode: "28110" },
  { locationName: "인천광역시 동구", regionCode: "28140" },
  { locationName: "인천광역시 미추홀구", regionCode: "28177" },
  { locationName: "인천광역시 연수구", regionCode: "28185" },
  { locationName: "인천광역시 남동구", regionCode: "28200" },
  { locationName: "인천광역시 부평구", regionCode: "28237" },
  { locationName: "인천광역시 계양구", regionCode: "28245" },
  { locationName: "인천광역시 서구", regionCode: "28260" },
  { locationName: "인천광역시 강화군", regionCode: "28710" },
  { locationName: "인천광역시 옹진군", regionCode: "28720" },
  { locationName: "광주광역시 동구", regionCode: "29110" },
  { locationName: "광주광역시 서구", regionCode: "29140" },
  { locationName: "광주광역시 남구", regionCode: "29155" },
  { locationName: "광주광역시 북구", regionCode: "29170" },
  { locationName: "광주광역시 광산구", regionCode: "29200" },
  { locationName: "대전광역시 동구", regionCode: "30110" },
  { locationName: "대전광역시 중구", regionCode: "30140" },
  { locationName: "대전광역시 서구", regionCode: "30170" },
  { locationName: "대전광역시 유성구", regionCode: "30200" },
  { locationName: "대전광역시 대덕구", regionCode: "30230" },
  { locationName: "울산광역시 중구", regionCode: "31110" },
  { locationName: "울산광역시 남구", regionCode: "31140" },
  { locationName: "울산광역시 동구", regionCode: "31170" },
  { locationName: "울산광역시 북구", regionCode: "31200" },
  { locationName: "울산광역시 울주군", regionCode: "31710" },
  { locationName: "경상북도 포항시", regionCode: "47110" },
  { locationName: "경상북도 포항시 남구", regionCode: "47111" },
  { locationName: "경상북도 포항시 북구", regionCode: "47113" },
  { locationName: "경상북도 경주시", regionCode: "47130" },
  { locationName: "경상북도 김천시", regionCode: "47150" },
  { locationName: "경상북도 안동시", regionCode: "47170" },
  { locationName: "경상북도 구미시", regionCode: "47190" },
  { locationName: "경상북도 영주시", regionCode: "47210" },
  { locationName: "경상북도 영천시", regionCode: "47230" },
  { locationName: "경상북도 상주시", regionCode: "47250" },
  { locationName: "경상북도 문경시", regionCode: "47280" },
  { locationName: "경상북도 경산시", regionCode: "47290" },
  { locationName: "경상북도 의성군", regionCode: "47730" },
  { locationName: "경상북도 청송군", regionCode: "47750" },
  { locationName: "경상북도 영양군", regionCode: "47760" },
  { locationName: "경상북도 영덕군", regionCode: "47770" },
  { locationName: "경상북도 청도군", regionCode: "47820" },
  { locationName: "경상북도 고령군", regionCode: "47830" },
  { locationName: "경상북도 성주군", regionCode: "47840" },
  { locationName: "경상북도 칠곡군", regionCode: "47850" },
  { locationName: "경상북도 예천군", regionCode: "47900" },
  { locationName: "경상북도 봉화군", regionCode: "47920" },
  { locationName: "경상북도 울진군", regionCode: "47930" },
  { locationName: "경상북도 울릉군", regionCode: "47940" },
  { locationName: "경상남도 창원시", regionCode: "48120" },
  { locationName: "경상남도 창원시 의창구", regionCode: "48121" },
  { locationName: "경상남도 창원시 성산구", regionCode: "48123" },
  { locationName: "경상남도 창원시 마산합포구", regionCode: "48125" },
  { locationName: "경상남도 창원시 마산회원구", regionCode: "48127" },
  { locationName: "경상남도 창원시 진해구", regionCode: "48129" },
  { locationName: "경상남도 사천시", regionCode: "48240" },
  { locationName: "경상남도 진주시", regionCode: "48170" },
  { locationName: "경상남도 통영시", regionCode: "48220" },
  { locationName: "경상남도 창녕군", regionCode: "48740" },
  { locationName: "경상남도 김해시", regionCode: "48250" },
  { locationName: "경상남도 밀양시", regionCode: "48270" },
  { locationName: "경상남도 거제시", regionCode: "48310" },
  { locationName: "경상남도 양산시", regionCode: "48330" },
  { locationName: "경상남도 의령군", regionCode: "48720" },
  { locationName: "경상남도 함안군", regionCode: "48730" },
  { locationName: "경상남도 고성군", regionCode: "48820" },
  { locationName: "경상남도 남해군", regionCode: "48840" },
  { locationName: "경상남도 하동군", regionCode: "48850" },
  { locationName: "경상남도 산청군", regionCode: "48860" },
  { locationName: "경상남도 함양군", regionCode: "48870" },
  { locationName: "경상남도 거창군", regionCode: "48880" },
  { locationName: "경상남도 합천군", regionCode: "48890" },
  { locationName: "전라남도 목포시", regionCode: "46110" },
  { locationName: "전라남도 여수시", regionCode: "46130" },
  { locationName: "전라남도 순천시", regionCode: "46150" },
  { locationName: "전라남도 나주시", regionCode: "46170" },
  { locationName: "전라남도 광양시", regionCode: "46230" },
  { locationName: "전라남도 담양군", regionCode: "46710" },
  { locationName: "전라남도 곡성군", regionCode: "46720" },
  { locationName: "전라남도 구례군", regionCode: "46730" },
  { locationName: "전라남도 고흥군", regionCode: "46770" },
  { locationName: "전라남도 보성군", regionCode: "46780" },
  { locationName: "전라남도 화순군", regionCode: "46790" },
  { locationName: "전라남도 장흥군", regionCode: "46800" },
  { locationName: "전라남도 강진군", regionCode: "46810" },
  { locationName: "전라남도 해남군", regionCode: "46820" },
  { locationName: "전라남도 영암군", regionCode: "46830" },
  { locationName: "전라남도 무안군", regionCode: "46840" },
  { locationName: "전라남도 함평군", regionCode: "46860" },
  { locationName: "전라남도 영광군", regionCode: "46870" },
  { locationName: "전라남도 장성군", regionCode: "46880" },
  { locationName: "전라남도 완도군", regionCode: "46890" },
  { locationName: "전라남도 진도군", regionCode: "46900" },
  { locationName: "전라남도 신안군", regionCode: "46910" },
  { locationName: "충청북도 청주시 상당구", regionCode: "43111" },
  { locationName: "충청북도 청주시", regionCode: "43110" },
  { locationName: "충청북도 청주시 서원구", regionCode: "43112" },
  { locationName: "충청북도 청주시 흥덕구", regionCode: "43113" },
  { locationName: "충청북도 청주시 청원구", regionCode: "43114" },
  { locationName: "충청북도 충주시", regionCode: "43130" },
  { locationName: "충청북도 제천시", regionCode: "43150" },
  { locationName: "충청북도 보은군", regionCode: "43720" },
  { locationName: "충청북도 옥천군", regionCode: "43730" },
  { locationName: "충청북도 영동군", regionCode: "43740" },
  { locationName: "충청북도 증평군", regionCode: "43745" },
  { locationName: "충청북도 진천군", regionCode: "43750" },
  { locationName: "충청북도 괴산군", regionCode: "43760" },
  { locationName: "충청북도 음성군", regionCode: "43770" },
  { locationName: "충청북도 단양군", regionCode: "43800" },
  { locationName: "충청남도 천안시", regionCode: "44130" },
  { locationName: "충청남도 천안시 동남구", regionCode: "44131" },
  { locationName: "충청남도 천안시 서북구", regionCode: "44133" },
  { locationName: "충청남도 공주시", regionCode: "44150" },
  { locationName: "충청남도 보령시", regionCode: "44180" },
  { locationName: "충청남도 아산시", regionCode: "44200" },
  { locationName: "충청남도 서산시", regionCode: "44210" },
  { locationName: "충청남도 논산시", regionCode: "44230" },
  { locationName: "충청남도 계룡시", regionCode: "44250" },
  { locationName: "충청남도 당진시", regionCode: "44270" },
  { locationName: "충청남도 금산군", regionCode: "44710" },
  { locationName: "충청남도 부여군", regionCode: "44760" },
  { locationName: "충청남도 서천군", regionCode: "44770" },
  { locationName: "충청남도 청양군", regionCode: "44790" },
  { locationName: "충청남도 홍성군", regionCode: "44800" },
  { locationName: "충청남도 예산군", regionCode: "44810" },
  { locationName: "충청남도 태안군", regionCode: "44825" },
  { locationName: "세종특별자치시", regionCode: "36110" },
  { locationName: "전북특별자치도 부안군", regionCode: "52800" },
  { locationName: "전북특별자치도 고창군", regionCode: "52790" },
  { locationName: "전북특별자치도 순창군", regionCode: "52770" },
  { locationName: "전북특별자치도 임실군", regionCode: "52750" },
  { locationName: "전북특별자치도 장수군", regionCode: "52740" },
  { locationName: "전북특별자치도 무주군", regionCode: "52730" },
  { locationName: "전북특별자치도 진안군", regionCode: "52720" },
  { locationName: "전북특별자치도 완주군", regionCode: "52710" },
  { locationName: "전북특별자치도 김제시", regionCode: "52210" },
  { locationName: "전북특별자치도 남원시", regionCode: "52190" },
  { locationName: "전북특별자치도 정읍시", regionCode: "52180" },
  { locationName: "전북특별자치도 익산시", regionCode: "52140" },
  { locationName: "전북특별자치도 군산시", regionCode: "52130" },
  { locationName: "전북특별자치도 전주시 덕진구", regionCode: "52113" },
  { locationName: "전북특별자치도 전주시", regionCode: "52110" },
  { locationName: "전북특별자치도 전주시 완산구", regionCode: "52111" },
  { locationName: "제주특별자치도 제주시", regionCode: "50110" },
  { locationName: "제주특별자치도 서귀포시", regionCode: "50130" },
  { locationName: "강원특별자치도 양양군", regionCode: "51830" },
  { locationName: "강원특별자치도 고성군", regionCode: "51820" },
  { locationName: "강원특별자치도 인제군", regionCode: "51810" },
  { locationName: "강원특별자치도 화천군", regionCode: "51790" },
  { locationName: "강원특별자치도 양구군", regionCode: "51800" },
  { locationName: "강원특별자치도 철원군", regionCode: "51780" },
  { locationName: "강원특별자치도 정선군", regionCode: "51770" },
  { locationName: "강원특별자치도 평창군", regionCode: "51760" },
  { locationName: "강원특별자치도 영월군", regionCode: "51750" },
  { locationName: "강원특별자치도 횡성군", regionCode: "51730" },
  { locationName: "강원특별자치도 홍천군", regionCode: "51720" },
  { locationName: "강원특별자치도 속초시", regionCode: "51210" },
  { locationName: "강원특별자치도 삼척시", regionCode: "51230" },
  { locationName: "강원특별자치도 태백시", regionCode: "51190" },
  { locationName: "강원특별자치도 동해시", regionCode: "51170" },
  { locationName: "강원특별자치도 강릉시", regionCode: "51150" },
  { locationName: "강원특별자치도 원주시", regionCode: "51130" },
  { locationName: "강원특별자치도 춘천시", regionCode: "51110" },
];
